[entrypoints]
internal = ["web"]
external = ["websecure"]

[ui]
show_status = true
open_in_new_tab = false

[routers."admin@docker"]
entrypoint = "web"
hide = true

[routers."photos@docker"]
entrypoint = "web"
application = "immich"
title = "Family photos"
icon = "catalog:immich"
group = "Media"
